settings:
  title: 'Status Page'
  url: 'https://status-page.uf3.cn' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: aupay.52nyg.com # unique identifier
    name: aupay.52nyg.com
    description: '授权中心.' # default=empty
    url: 'https://aupay.52nyg.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: blog.52nyg.com
    name: blog.52nyg.com
    description: '博客.'
    url: 'https://blog.52nyg.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: files.52nyg.com
    name: 文件中心
    url: 'https://files.52nyg.com/'
    method: GET
    expectStatus: 200
    
  - id: pan.uf3.cn
    name: 网盘
    url: 'https://pan.uf3.cn/'
    method: GET
    
  - id: xopan.uf3.cn
    name: 网盘节点
    url: 'https://xopan.uf3.cn/'
    method: GET
    expectStatus: 200
